# Serial Manager Node Parameters
serial_manager:
  ros__parameters:
    serial_port: "/dev/ttyACM0"       # Serial port for ESP32
    baud_rate: 115200                 # Baud rate
    serial_timeout_sec: 2.0           # Timeout before attempting reconnection
    wheel_circumference: 0.3078       # Used to decode from the esp32. 

imu_publisher:
  ros__parameters:
    topic_name: "imu"
    sample_freq_mill: 10 # sample frequency in milliseconds.

ackermann_ekf_node:
  ros__parameters:
    wheel_base: 0.178
    control_buffer_size: 10
    publish_rate_hz: 20

    # state_vector = [x, y, theta, v]
    Q_covariance: [0.00001, 0.0, 0.0, 0.0, 
                    0.0, 0.00001, 0.0, 0.0, 
                    0.0, 0.0, 1.0, 0.0, 
                    0.0, 0.0, 0.0, 1.0]

    # z = [theta_measured, v_measured]
    R_covariance: [0.0001, 0.0, # theta
                  0.0, 0.0001] # v