# Serial Manager Node Parameters
serial_manager:
  ros__parameters:
    serial_port: "/dev/ttyACM0"       # Serial port for ESP32
    baud_rate: 115200                 # Baud rate
    serial_timeout_sec: 2.0           # Timeout before attempting reconnection
    wheel_circumference: 0.3078       # Used to decode from the esp32. 

# Odometry Node Parameters  
odometry_node:
  ros__parameters:
    # Vehicle geometry
    wheelbase:  0.178                    # Distance between front and rear axles (meters)
    max_steering_angle: 0.4363326           # Maximum steering angle (radians, ~25 degrees)
    wheel_circumference: 0.3078       # Used to decode from the esp32.
    
    # Frame configuration
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: false                  # Whether to publish TF transforms

# Control Node Parameters
control_node:
  ros__parameters:

    # Motion limits
    wheelbase:  0.178                    # Distance between front and rear axles (meters)
    max_steering_angle: 0.4363326           # Maximum steering angle (radians, ~25 degrees)
    max_speed: 2.0
    
    # Safety
    cmd_timeout_sec: 0.5

imu_publisher:
  ros__parameters:
    topic_name: "imu"
    sample_freq_mill: 50  # sample freqeuncy in milliseconds.